### ISSUE TITLE
Improve development setup

### ISSUE THREAD

**Issue by NickStemerdink** [LionwareSolutions/Fluxa#3]
The current setup requires some manual and undocumented steps to get Fluxa up and running.

Setup should ideally be as simple as `$ docker compose up`. If manual actions are needed they need to be documented in the README.

**Comment by KarloDerEchte** [comment]
Please also remove the SSL requirement too. The user should set up that himself if he wants that.

**Comment by NickStemerdink** [comment]
I've made the necessary changes to make localhost work on http by default.

Running `composer install` in the Dockerfile has other consequences, I'd like to investigate that separate from this issue. Can you create a new ticket for that with a motivation for that change? I'd also like to get the opinion of other people what are best practices regarding this.
